### PR TITLE
Updated links

### PR DESCRIPTION
**Pull request by necromaniac**
Hey,

I removed some broken and outdated links and added a few ressources I find useful.

### CODE REVIEW

**Comment by ericdouglas** [comment]
@necromaniac thank you for your help!

The link *"Meteor's new $11.2 million development budget"* and *"Meteor Jobs"* in the More Useful Links section aren't broken.

Can you return those links and create another commit before I merge you PR?

**Comment by necromaniac** [comment]
Yea I could, but the budget-link is from 2012 and the other one is a twitter account posting random ads for games, so I thought I'd remove them.

**Comment by ericdouglas** [comment]
@necromaniac you're right! Let's remove the meteor jobs link! I think that the dev budget is still relevant. Maybe they don't spend all this money yet :laughing:

**Comment by necromaniac** [comment]
Haha okay, you can merge now.

**Comment by ericdouglas** [comment]
@necromaniac thank you! :tada:

**Pull request merged**
